Repository QuizBank-Dev/QuizBank-BE, pull requests merged in 2025-05, with the labels that each got.

#59 [Feat] 그룹 관련 API 수정
  src/modules/group/group-quizbook/group-quizbook.service.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.service.ts
Labels: ✨ Feature, ♻️ Refactor

#60 [Feat] Quizbook 상세조회 API 분기
  src/database/database.module.ts
  src/modules/comment/schema/comment.schema.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.example.ts
  src/modules/quizbook/quizbook.repository.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/quizbook/schema/quizbook.schema.ts
  src/modules/review/schema/review.schema.ts
  src/modules/study-log/schema/study-log.schema.ts
  src/modules/study/schema/quiz-record.schema.ts
  src/modules/study/schema/quizbook-record.schema.ts
  src/modules/study/study.example.ts
  src/modules/study/study.repository.ts
  src/modules/study/study.service.ts
Labels: ✨ Feature

#62 [Feat] 소켓 채팅 송수신 로직 및 채팅 내역 조회 API 수정
  src/modules/chat/chat.gateway.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/repository/chat.repository.ts
Labels: ✨ Feature, ♻️ Refactor

#65 [Feat] 나의 그룹 목록 조회 API 수정 및 소켓 이벤트 핸들러 추가
  src/modules/chat/chat.gateway.ts
  src/modules/group/group.example.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
Labels: ✨ Feature, ♻️ Refactor

#67 [Fix] 로그아웃 오류 수정
  src/modules/auth/auth.service.ts
Labels: 🐛 Fix

#68 [Refactor] 생성 관련 API 응답값 result 추가
  src/modules/comment/comment.controller.ts
  src/modules/comment/comment.example.ts
  src/modules/comment/comment.service.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.example.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/review/review.controller.ts
  src/modules/review/review.example.ts
  src/modules/review/review.service.ts
Labels: ♻️ Refactor

#71 [Refactor] 메타데이터 조회 API 응답값에 createdAt 추가
  src/modules/quizbook/quizbook.example.ts
  src/modules/quizbook/quizbook.repository.ts
Labels: ♻️ Refactor

#70 [Feat] 그룹 선정 문제집 리스트 조회 API 수정
  src/modules/group/group-quizbook/dto/group-quizbook-query.dto.ts
  src/modules/group/group-quizbook/group-quizbook.example.ts
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group-quizbook/group-quizbook.service.ts
Labels: ✨ Feature, ♻️ Refactor

#73 [Fix] 로그인 오류 수정
  src/modules/auth/auth.service.ts
Labels: 🐛 Fix

#75 [Refactor] 요청사항 수정 및 버그 수정
  src/modules/group/group.repository.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/review/review.controller.ts
  src/modules/study/dto/submit-study.dto.ts
  src/modules/study/schema/quiz-record.schema.ts
  src/modules/study/study.example.ts
  src/modules/study/study.service.ts
Labels: 🐛 Fix, ♻️ Refactor

#76 [Fix] 그룹 멤버별 점수 조회 API 오류 수정
  src/modules/study/study.service.ts
Labels: 🐛 Fix

#79 [Feat] 그룹 관련 api 추가 및 수정
  src/modules/group/group-quizbook/group-quizbook.controller.ts
  src/modules/group/group-quizbook/group-quizbook.example.ts
  src/modules/group/group-quizbook/group-quizbook.module.ts
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group-quizbook/group-quizbook.service.ts
  src/modules/group/group-quizbook/schema/group-quizbook.schema.ts
  src/modules/group/group.service.ts
  src/modules/study/study.repository.ts
Labels: ✨ Feature

#82 [Feat] Study 결과 리스트 조회 API 추가
  .github/workflows/deploy-develop.yml
  src/modules/like/like.repository.ts
  src/modules/study/study.controller.ts
  src/modules/study/study.example.ts
  src/modules/study/study.repository.ts
  src/modules/study/study.service.ts
Labels: ✨ Feature, ♻️ Refactor

#81 [Feat] 비밀번호 변경 / 비밀번호 초기화(재설정) API 구현
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/auth/auth-token/auth-token.providers.ts
  src/modules/auth/auth-token/auth-token.service.ts
  src/modules/auth/auth-token/auth-token.types.ts
  src/modules/auth/auth.const.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/reset-password/dto/confirm-reset-password.dto.ts
  src/modules/auth/reset-password/dto/request-reset-password.dto.ts
  src/modules/auth/reset-password/reset-password.const.ts
  src/modules/auth/reset-password/reset-password.controller.ts
  src/modules/auth/reset-password/reset-password.module.ts
  src/modules/auth/reset-password/reset-password.service.ts
  src/modules/auth/reset-password/schema/reset-password.schema.ts
  src/modules/user/dto/change-password.dto.ts
  src/modules/user/user.repository.ts
Labels: ✨ Feature

#83 [Feat] 모든 그룹 선정문제집 조회 API 추가
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group.repository.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.example.ts
  src/modules/quizbook/quizbook.module.ts
  src/modules/quizbook/quizbook.service.ts
Labels: ✨ Feature

#86 [Fix] 쿠키 설정 방식 수정
  src/modules/auth/auth.service.ts
Labels: 🐛 Fix, 🚀 Deploy

#87 [Fix] 쿠키 설정 방식 수정
  src/modules/auth/auth.service.ts
Labels: 🐛 Fix, 🚀 Deploy

#89 [Fix] 작업을 위해 사용한 코드 정리 및 로그아웃 쿠키 제거
  src/modules/auth/auth.service.ts
Labels: 🐛 Fix, 🚀 Deploy
