Repository QuizBank-Dev/QuizBank-BE, pull requests merged in 2025-04, with the labels that each got.

#25 [Feat] Group Member 관련 API 구현
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/auth/auth-token/auth-token.providers.ts
  src/modules/auth/auth-token/auth-token.service.ts
  src/modules/auth/auth-token/auth-token.types.ts
  src/modules/auth/auth.const.ts
  src/modules/group/dto/create-group-member.dto.ts
  src/modules/group/dto/invite-token-payload.dto.ts
  src/modules/group/dto/update-owner.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.example.ts
  src/modules/group/group.module.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
  src/modules/group/schema/group-quizbook.schema.ts
  src/modules/quiz/quiz.repository.ts
  src/modules/quizbook/quizbook.repository.ts
Labels: ✨ Feature

#28 [Config] 클라우드 타입 자동배포 workflow 환경변수 정보 업데이트
  .github/workflows/deploy-develop.yml
Labels: ⚙️ Config

#29 [Feat] Group 선정 문제집 관련 API 구현
  src/app.module.ts
  src/modules/group/group-quizbook/dto/create-group-quizbook.dto.ts
  src/modules/group/group-quizbook/group-quizbook.controller.ts
  src/modules/group/group-quizbook/group-quizbook.example.ts
  src/modules/group/group-quizbook/group-quizbook.module.ts
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group-quizbook/group-quizbook.service.ts
  src/modules/group/group-quizbook/schema/group-quizbook.schema.ts
  src/modules/group/group.module.ts
  src/modules/group/group.service.ts
Labels: ✨ Feature

#31 [Feat] Group API에 GroupQuizbook 관련 로직 추가
  src/modules/group/group-quizbook/group-quizbook.module.ts
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group-quizbook/group-quizbook.service.ts
  src/modules/group/group.module.ts
  src/modules/group/group.service.ts
Labels: ✨ Feature

#32 [Feat] User 관련 API 개발
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/email-code/email-code.service.ts
  src/modules/category/category.controller.ts
  src/modules/category/category.module.ts
  src/modules/category/category.service.ts
  src/modules/category/dto/update-categories.dto.ts
  src/modules/follow/dto/follow-query.dto.ts
  src/modules/follow/follow.controller.ts
  src/modules/follow/follow.example.ts
  src/modules/follow/follow.module.ts
  src/modules/follow/follow.service.ts
  src/modules/upload/upload.module.ts
  src/modules/upload/upload.providers.ts
  src/modules/upload/upload.service.ts
  src/modules/user/dto/update-profile.dto.ts
  src/modules/user/schema/user.schema.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.example.ts
  src/modules/user/user.module.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
Labels: ✨ Feature

#36 [Feat] ChatModule 구현
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.example.ts
  src/modules/chat/chat.gateway.ts
  src/modules/chat/chat.module.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/chat-query.dto.ts
  src/modules/chat/dto/chat.dto.ts
  src/modules/chat/filter/socket-exception.filter.ts
  src/modules/chat/repository/chat-room.repository.ts
  src/modules/chat/repository/chat.repository.ts
  src/modules/chat/repository/read-status.repository.ts
  src/modules/chat/schema/chat-room.schema.ts
  src/modules/chat/schema/chat.schema.ts
  src/modules/chat/schema/read-status.schema.ts
  src/modules/group/group.example.ts
  src/modules/group/group.module.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
  src/modules/group/schema/group.schema.ts
Labels: ✨ Feature

#37 [Feat] GitHub 로그인 구현
  package.json
  pnpm-lock.yaml
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guard/dynamic-auth.guard.ts
  src/modules/auth/strategy/github.strategy.ts
  src/modules/user/dto/oauth-login.dto.ts
  src/modules/user/schema/user.schema.ts
  src/modules/user/user.repository.ts
Labels: ✨ Feature

#40 [Feat] Group 및 Chat 관련 api 수정 및 추가
  src/modules/chat/chat.service.ts
  src/modules/chat/repository/chat.repository.ts
  src/modules/group/dto/group-query.dto.ts
  src/modules/group/dto/patch-respond-application.dto.ts
  src/modules/group/group-quizbook/dto/create-group-quizbook.dto.ts
  src/modules/group/group-quizbook/dto/group-quizbook-query.dto.ts
  src/modules/group/group-quizbook/group-quizbook.controller.ts
  src/modules/group/group-quizbook/group-quizbook.example.ts
  src/modules/group/group-quizbook/group-quizbook.repository.ts
  src/modules/group/group-quizbook/group-quizbook.service.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.example.ts
  src/modules/group/group.module.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
  src/modules/group/schema/group.schema.ts
Labels: ✨ Feature, ♻️ Refactor

#42 [Fix] Group, ReadStatus Repository 수정
  src/modules/chat/repository/read-status.repository.ts
  src/modules/group/group.module.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
Labels: 🐛 Fix

#44 [Config] 자동배포 관련 Workflow 환경변수 업데이트
  .github/workflows/deploy-develop.yml
  src/modules/user/dto/update-profile.dto.ts
Labels: 🐛 Fix, ⚙️ Config

#46 [Feat] AI 연동 채점 기능 개발
  .github/workflows/deploy-develop.yml
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/ai/ai.module.ts
  src/modules/ai/ai.service.ts
  src/modules/ai/ai.types.ts
  src/modules/ai/client/gemini-client.ts
  src/modules/ai/prompt/longAnswer.prompt.ts
  src/modules/ai/prompt/modelAnswer.prompt.ts
  src/modules/ai/prompt/shortAnswer.prompt.ts
  src/modules/ai/utils/ai.utils.ts
  src/modules/quiz/dto/create-quiz.dto.ts
  src/modules/quiz/quiz.repository.ts
  src/modules/quiz/schema/quiz.schema.ts
  src/modules/quizbook/quizbook.module.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/quizbook/schema/quizbook.schema.ts
  src/modules/study/schema/quiz-record.schema.ts
  src/modules/study/study.module.ts
  src/modules/study/study.service.ts
  src/modules/study/utils/study.utils.ts
Labels: ✨ Feature

#47 [Feat] User/Auth 관련 로직 수정
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/follow/follow.controller.ts
  src/modules/follow/follow.module.ts
  src/modules/follow/follow.service.ts
  src/modules/study-log/study-log.repository.ts
  src/modules/study-log/study-log.service.ts
  src/modules/user/schema/user.schema.ts
  src/modules/user/user.controller.ts
  src/modules/user/user.example.ts
  src/modules/user/user.repository.ts
  src/modules/user/user.service.ts
Labels: ✨ Feature, ♻️ Refactor

#48 [Feat] 모든 그룹 목록 조회 api 추가
  src/modules/auth/auth.service.ts
  src/modules/group/dto/group-query.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.example.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
Labels: ✨ Feature, ♻️ Refactor

#50 [Feat] 학습 제출 시 사용자 경험치 증가 로직 개발
  src/modules/study-log/study-log.repository.ts
  src/modules/study/study.module.ts
  src/modules/study/study.service.ts
  src/modules/user/user.repository.ts
Labels: ✨ Feature

#52 [Feat] 내 정보 조회 API 수정
  src/modules/user/user.controller.ts
Labels: ✨ Feature, ♻️ Refactor
