Repository QuizBank-Dev/QuizBank-BE, pull requests merged in 2025-03, with the labels that each got.

#2 [Config] 자동 배포 Workflows 생성
  .github/workflows/deploy-develop.yml
Labels: 👷 CI/CD

#5 [Config] Build 테스트 Workflows 생성
  .github/workflows/build-check.yml
Labels: 👷 CI/CD

#6 [Feat] 기본 리소스 생성 및 DB 스키마 정의
  src/app.module.ts
  src/database/database.const.ts
  src/database/database.providers.ts
  src/modules/comment/comment.controller.ts
  src/modules/comment/comment.module.ts
  src/modules/comment/comment.service.ts
  src/modules/comment/dto/create-comment.dto.ts
  src/modules/comment/dto/update-comment.dto.ts
  src/modules/comment/entities/comment.entity.ts
  src/modules/comment/schema/comment.schema.ts
  src/modules/quiz/dto/create-quiz.dto.ts
  src/modules/quiz/dto/update-quiz.dto.ts
  src/modules/quiz/entities/quiz.entity.ts
  src/modules/quiz/quiz.controller.ts
  src/modules/quiz/quiz.module.ts
  src/modules/quiz/quiz.service.ts
  src/modules/quiz/schema/quiz-again.schema.ts
  src/modules/quiz/schema/quiz-record.schema.ts
  src/modules/quiz/schema/quiz.schema.ts
  src/modules/quizbook/dto/create-quizbook.dto.ts
  src/modules/quizbook/dto/update-quizbook.dto.ts
  src/modules/quizbook/entities/quizbook.entity.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.module.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/quizbook/schema/quizbook-like.schema.ts
  src/modules/quizbook/schema/quizbook-record.schema.ts
  src/modules/quizbook/schema/quizbook.schema.ts
  src/modules/review/dto/create-review.dto.ts
  src/modules/review/dto/update-review.dto.ts
  src/modules/review/entities/review.entity.ts
  src/modules/review/review.controller.ts
  src/modules/review/review.module.ts
  src/modules/review/review.service.ts
  src/modules/review/schema/review.schema.ts
Labels: ✨ Feature

#8 [FEAT] DB 스키마 정의
  src/modules/auth/email-code/schema/email-code.schema.ts
  src/modules/user/schema/user.schema.ts
Labels: ✨ Feature

#11 [Feat] MailerModule 구현
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/config/env.const.ts
  src/config/env.validation.ts
  src/modules/mailer/mailer.module.ts
  src/modules/mailer/mailer.providers.ts
  src/modules/mailer/mailer.service.ts
Labels: ✨ Feature

#12 [Config] DB연결 로직 변경
  eslint.config.mjs
  src/database/database.const.ts
  src/database/database.module.ts
  src/database/database.providers.ts
Labels: ⚙️ Config

#15 [Fix] 다중 DB 연결 오류 로직 수정
  src/database/database.module.ts
Labels: 🐛 Fix

#16 [Feat] Quizbook 관련 API 구현
  src/common/decorators/base-response.decorator.ts
  src/common/dto/base-response.dto.ts
  src/common/interceptors/global-response.interceptor.ts
  src/main.ts
  src/modules/quiz/dto/create-quiz.dto.ts
  src/modules/quiz/dto/update-quiz.dto.ts
  src/modules/quiz/entities/quiz.entity.ts
  src/modules/quiz/quiz.controller.ts
  src/modules/quiz/quiz.module.ts
  src/modules/quiz/quiz.service.ts
  src/modules/quiz/schema/quiz.schema.ts
  src/modules/quizbook/dto/create-quizbook.dto.ts
  src/modules/quizbook/dto/find-all-quizbook.dto.ts
  src/modules/quizbook/dto/response-quizbook.dto.ts
  src/modules/quizbook/dto/update-quizbook.dto.ts
  src/modules/quizbook/entities/quizbook.entity.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.module.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/quizbook/schema/quizbook.schema.ts
Labels: ✨ Feature

#20 [Feat] 그룹 정보 관련 DB 스키마 정의
  src/modules/group/schema/group-quizbook.schema.ts
  src/modules/group/schema/group.schema.ts
Labels: ✨ Feature

#22 [Feat] Review, Comment 관련 API 개발
  .github/workflows/build-check.yml
  package.json
  pnpm-lock.yaml
  src/app.module.ts
  src/common/decorators/base-response.decorator.ts
  src/common/decorators/user-id.decorator.ts
  src/common/dto/base-response.dto.ts
  src/common/dto/default-response.dto.ts
  src/common/utils/database.util.ts
  src/database/database.module.ts
  src/database/database.service.ts
  src/modules/comment/comment.controller.ts
  src/modules/comment/comment.example.ts
  src/modules/comment/comment.module.ts
  src/modules/comment/comment.repository.ts
  src/modules/comment/comment.service.ts
  src/modules/comment/dto/create-comment.dto.ts
  src/modules/comment/dto/update-comment.dto.ts
  src/modules/comment/entities/comment.entity.ts
  src/modules/comment/schema/comment.schema.ts
  src/modules/quiz/dto/create-quiz.dto.ts
  src/modules/quiz/quiz.controller.ts
  src/modules/quiz/quiz.example.ts
  src/modules/quiz/quiz.module.ts
  src/modules/quiz/quiz.repository.ts
  src/modules/quiz/quiz.service.ts
  src/modules/quiz/schema/quiz.schema.ts
  src/modules/quizbook/dto/create-quizbook.dto.ts
  src/modules/quizbook/dto/find-all-quizbook.dto.ts
  src/modules/quizbook/dto/response-quizbook.dto.ts
  src/modules/quizbook/quizbook.controller.ts
  src/modules/quizbook/quizbook.example.ts
  src/modules/quizbook/quizbook.module.ts
  src/modules/quizbook/quizbook.repository.ts
  src/modules/quizbook/quizbook.service.ts
  src/modules/quizbook/schema/quizbook.schema.ts
  src/modules/review/dto/create-review.dto.ts
  src/modules/review/dto/update-review.dto.ts
  src/modules/review/entities/review.entity.ts
  src/modules/review/review.controller.ts
  src/modules/review/review.example.ts
  src/modules/review/review.module.ts
  src/modules/review/review.repository.ts
  src/modules/review/review.service.ts
  src/modules/review/schema/review.schema.ts
  src/modules/user/schema/user.schema.ts
Labels: ✨ Feature

#24 [Feat] Group CRUD 관련 API 구현
  src/app.module.ts
  src/modules/group/dto/create-group.dto.ts
  src/modules/group/group.controller.ts
  src/modules/group/group.example.ts
  src/modules/group/group.module.ts
  src/modules/group/group.repository.ts
  src/modules/group/group.service.ts
  src/modules/group/schema/group-quizbook.schema.ts
  src/modules/group/schema/group.schema.ts
  src/modules/quiz/quiz.repository.ts
  src/modules/quizbook/quizbook.repository.ts
Labels: ✨ Feature
